### ISSUE TITLE
NU5128 shows up on packing

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer-template#1]
Running `dotnet pack` on the project leads to the following warning:

```
C:\Program Files\dotnet\sdk\3.1.101\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [C:\Users\isaac\code\farmer-template\farmer.template.proj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5128: - Add lib or ref assemblies for the netstandard2.0 target framework [C:\Users\isaac\code\farmer-template\farmer.template.proj]
```

I have no idea why or how to remove it. The docs for this error talk about nuspec files - but we have no nuspec here.

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128

**Comment by kirkone** [comment]
The interesting Part ist, that the nuget file ist created anyway 🤨

**Comment by kirkone** [comment]
Adding:

`<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>`

Solved the problem. it seems to be the right way because you do not have any dependencies.

In the docs link is mentioned:

> **Remove all dependencies for packages that are not related to assemblies**
If your package does not contain any lib/ or ref/ files and is not a meta-package, it likely does not have any dependencies that the package consumer needs. If you are packing with NuGet's MSBuild Pack target, you can set  `<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>` in any PropertyGroup in your project file. If you are using a custom nuspec file, remove the `<dependencies>` element.

**Comment by isaacabraham** [comment]
Works - thank you!
